sassoftware/python-dlpy

dlpy/model.py
This parameter is not supported in Viya 3.3
=> removed randomMutation as default parameter in dlExportModel

dlpy/images.py
Create random mutations from set of images
=> Added random_mutations to ImageTable

dlpy/images.py, dlpy/model.py
Fixed comments by Kevin and fixed a bug Alex pointed out in regards to being able to use the gpu. Also made the code to flow better.
=> Dlpy fix pull comments

dlpy/model.py
Fixed bug in heat_map_analysis caused display of heatmap to be same for all images.
=> fixed bug in heat_map_analysis 

dlpy/images.py
There was an issue with show not working sometimes so added plt.show() as in gitlab version.
=> Added plt.show() to end of images.show function

dlpy/model.py
=> Add DLPyError for empty table in get_feature_maps

examples/Example7-SimpleObjectDetection.ipynb
Update some cells which refer to `model` instead of `yolo_model`
=> Minor update to Example7-SimpleObjectDetection

dlpy/model_conversion/sas_onnx_parse.py, dlpy/model_conversion/write_onnx_model.py, dlpy/tests/test_model.py
Resolve #51: This pull request adds support for ImageScaler op when importing / exporting ONNX models.
=> Add ImageScaler for input image scale and offset

examples/onnx/DLPy_Export_ONNX.ipynb
Update example with narrative.
=> Update DLPy Export ONNX example

dlpy/utils.py
Changes include:
dlpy/utils.py: clean code in the function: create_object_detection_table. Besides, I remove a duplicate variable, idjoin, in det_img_table which would cause an error in vb025. The changes work properly on vb015 as well.
=> remove a duplicate variable, idjoin, in det_img_table

README.md
These new video links point to a single video on YouTube that you can navigate with time indexes - located on the SAS Users channel.
=> Updated separate video links to single YouTube version with time indexes

dlpy/model_conversion/write_keras_model_parm.py, dlpy/network.py
Added error handling for automatic Keras model conversion.  DLPy error messages will now be thrown when HDF5 files are not present or are mis-specified in some way (e.g. not fully qualified path, misspelled, etc.).  Also did some PEP-8 cleanup.
=> PEP-8 cleanup and add informative error message.

dlpy/layers.py, dlpy/model.py, dlpy/network.py, dlpy/tests/test_model.py, dlpy/tests/test_network.py
I have a fix to functional API and plot_training_history. The involved files are:
dlpy/layers.py: make an abstract class for convolution type layer which is useful for the next release; support tensor shape calculation;
dlpy/model.py: fix a bug when plotting training history
dlpy/network.py: enable model_table and model_weights for functional API
dlpy/tests/test_network.py
=> functional API fixes

dlpy/tests/test_applications.py, dlpy/tests/test_utils.py
Added and updated unittests in test_applications.py and test_utils.py
=> Added additional unittests

dlpy/tests/test_imagetable.py, dlpy/tests/test_model.py, dlpy/tests/test_utils.py, dlpy/utils.py
Added unittests to test_utils.py, test_imagetable.py, test_model.py
=> Added more unittests

dlpy/applications.py
The push aims to support pre-defined UNet. The tests will be added once CAS server is back.
=> support Unet

dlpy/applications.py, dlpy/tests/test_applications.py
add an option to append bn after conv in UNet and two tests
=> add an option to append bn after conv in UNet and two tests

dlpy/speech.py, dlpy/speech_utils.py, examples/speech_recognition/AudioTraining.ipynb, examples/speech_recognition/SpeechToText.ipynb, examples/speech_recognition/TrainingSpeechRecognitionModel.ipynb
As title. Code not changed in speech.py and speech_utils.py. All unit tests passed.
=> Change code documentation and example notebook modified based on Alex's review

dlpy/lr_scheduler.py
I plan to push more explanation for lr policies.
The affected file is dlpy/lr_scheduler.py.
=> more explanation for lr_schedular

dlpy/applications/darknet.py, dlpy/applications/densenet.py, dlpy/applications/inception.py, dlpy/applications/mobilenet.py, dlpy/applications/rcnn.py, dlpy/applications/resnet.py, dlpy/applications/shufflenet.py, dlpy/applications/unet.py, dlpy/applications/vgg.py, dlpy/applications/yolo.py, dlpy/caffe_models/model_resnet101.py, dlpy/caffe_models/model_resnet152.py, dlpy/caffe_models/model_resnet50.py, dlpy/caffe_models/model_vgg16.py, dlpy/caffe_models/model_vgg19.py, dlpy/keras_models/model_inceptionv3.py, dlpy/model.py, dlpy/tests/test_applications.py
Always use None if DLPy defaults match the server defaults.
Use locals() to get the input parameters for the input layer.
the tests in test_model and test_application are clean.
=> Polish all the predefined models and fix #213

dlpy/utils.py
A few dlpy methods didn't work on power and this fixed my issues. It might also prove helpful for #222
=> fix get_cas_host_type to support Power Linux

dlpy/model.py
test_model.py passes without any issues.
=> added random options into predict and evaluate

dlpy/network.py, dlpy/tests/test_model.py, dlpy/tests/test_utils.py, dlpy/utils.py
The changes fix an issue when loading weights attribute table. Besides, I add a helper function called file_exist_on_server() in utils.py. The function is a client-side version of os.path.exists.
=> fix a bug when loading weights attr

dlpy/model.py, dlpy/tests/test_transformers.py, dlpy/transformers/bert_model.py, dlpy/transformers/bert_utils.py
New code to fix a minor bug (layer output in RNN models) and add support for a broader range of BERT models.  We now support BERT, RoBERTa, and DistilBERT from the HuggingFace pre-trained model repository.  I also fixed the code that prepares data for a sequence labeling task.  Previously this code had not been exercised, so the existing bugs were not exposed.
=> BERT updates to support RoBERTa and DistilBERT

dlpy/layers.py, dlpy/network.py, dlpy/tests/datasources/sample_syntax_for_test.json, dlpy/tests/test_layers.py, dlpy/tests/test_network.py, dlpy/tests/test_transformers.py
Please help me review the PR.
The PR contains the changes as follows:
1. Added more operators in layers.py, including Split, Survival, Clustering, FCMPLayer
2. Implemented all extractors for existing operators, including fcmp, segmentation, embeddingloss, cluster, survival, split. Besides, I propose to add a check for unsupported operators to be extracted from a table.
3. Testcases covering the changes.
4. Remove distance argument in embedding loss layer because it is a hidden option.
=> NEW FEATURE: Adding Split, Survival, Clustering, FCMPLayer

examples/transformers/bert_data_preparation_quickstart.ipynb, examples/transformers/qnli_glue_task.ipynb
Updated BERT data preparation and GLUE task examples to incorporate changes to APIs and arguments pushed previously.
=> Update examples to reflect changes in function name(s) and argument(s).

examples/quick_start/Pre-trainedModels_TransferLearning.ipynb
PretrainedModels_TransferLearning ready for diff and merge
=> Ran PretrainedModels_TransferLearning end to end with changes.

dlpy/tests/test_model_conversion.py
Since we don't have a mechanism to detect whether a Viya server has a GPU or not, the automated RNN conversion tests were skipping any tests that required a GPU.  However, this was still causing errors even though none of the tests were called.  A similar error was noted in issue [26600 ](https://github.com/tensorflow/tensorflow/issues/26600)on the Tensorflow GitHub.  The solution for that issue seemed to be to get the environment to configure/recognize the GPU.  Since that won't work in our scenario, I removed all code references to GPU-based layers.  I was able to successfully run the code with a Windows client and a Linux server (Keras version 2.3.1, Tensorflow version 1.13.1).
=> Remove CUDNN RNN references causing errors in automated tests

examples/image_classification/Image_Classification_Fruits_With_EfficientNet.ipynb
update CAS connection with generic information
=> fix generic session information

examples/image_denoising/README.md
Cleaned up notebook with image denoising example.
=> New autoencoder denoising example.

dlpy/utils.py
Mismatch in list lengths for xticks and xticklabels.
=> Bug fix for predicted_prob_barplot.

dlpy/image_captioning.py, dlpy/image_embedding.py, dlpy/timeseries.py, doc/source/api.rst
This pull request is to surface content that already has docstrings, but is unsurfaced in the API documentation. The PR contributes only changes to the documentation source. The HTML still needs to be regenerated and uploaded to the gh-pages branch in order to for the changes to be reflected in the online documentation. 
I attached a txt file summarizing the changes by module.
[DLPy_Updates.txt](https://github.com/sassoftware/python-dlpy/files/5195448/DLPy_Updates.txt)
=> Update documentation content

doc/source/building_models.rst, doc/source/index.rst, examples/functional_model/Build_Models_With_Functional_API.ipynb
This commit adds a page to the dlpy documentation. It also updates the index to show the new page and fixes
spelling in the example notebook that motivated this page.
Note that this is just an update to the rst files. In order for the doc to reflect these changes, we need to run Sphinx and update the html files in the gh-pages branch. Please reach out if I can be of assistance for that.
=> Adding bulding_model.rst (Documentation for model-building API)

dlpy/audio.py, dlpy/images.py, dlpy/timeseries.py
This PR adds examples to the docstrings so they will be included on the API doc pages.
=> Add examples for API doc

dlpy/applications/enet.py, dlpy/model_conversion/write_onnx_model.py, dlpy/tests/test_audio.py, dlpy/tests/test_model.py, dlpy/tests/test_onnx_model.py, dlpy/tests/test_transformers.py, dlpy/tests/test_utils.py, dlpy/utils.py
1) Reincorporated fix from previous pull request (issue #325) because master branch had changed substantially since the pull request submitted.
2) Fixed bug mentioned in issue #330.
3) Reworked/enhanced some unit tests for better reliability
4) Fixed minor bugs related to CASLIB handling.
=> Address issues #325 and #330 plus miscellaneous bug fixes

dlpy/tests/test_utils.py, dlpy/utils.py
1. Enhanced visualization for one channel (gray-scale) images for object detection.
2. Enhanced visualization for ground truth and predictions for semantic segmentation.
3. Fixed bug in certain APIs().
=> Better visualization for gray-scale images and bug fixing

examples/tabular_data_analysis/Regression_with_Fully_Connected_Neural_Network.ipynb
Updated the DLPy tabular data FC Neural Network Regression example. Better narrative, validated results, reproducible by users.
=> Updated DLPy tabular FCNN Regression example. Runs end-to-end with public available scikit-Learn data

dlpy/transformers/bert_model.py
Simple fix for problem reported by @anttiheino.  Unit tests run cleanly.
=> Fix for issue #361

dlpy/model_conversion/write_keras_model_parm.py, dlpy/network.py, dlpy/tests/test_model.py, dlpy/transformers/bert_model.py
This pull request includes a fix for issue #367 and an update to the unit tests to make them run more reliably.  I also a change that should ease compatibility with Keras for versions 2.3.0 and later.
=> Fix bug reading Finnish BERT model and miscellaneous cleanup/bug-fixes.

dlpy/datasources/mztrain.yaml, dlpy/image_embedding.py, dlpy/mzmodel.py, dlpy/tests/test_mzmodel.py, dlpy/tests/test_onnx_model.py, dlpy/tests/test_utils.py
1. fix existing unit tests
2. add more tests for mzmodel
=> Unit test fix
