- dlpy/images.py
- dlpy/model.py
I used some changes from Alex pull request and combined with my own. 
heat_map_analysis has the following additional features:
- set img_type to 'A', 'M' or 'C' to get all, misclassified or correctly classified images respectively
-pass a list of _id_ ' s or a singing _id_ value to image_id to run heatmap on specific images
- pass a list of filenames or a single filename to get heatmaps on the images containing that filename
image_id is unique while filename is not thus image_id overrides filename if both are passed into the function
- can also display more or less than 5 images by setting max_display
Additionally:
-_id_ was added to the ImageTable
-the model.py attributes documentation was updated
-An attribute valid_res_tbl was added so that the results from predict() can be further …
> heat_map_analysis update to allow selecting misclassified images and images by id or filename

- dlpy/model.py
Now raises ValueError if pass in a filename into model.heat_map_analysis that does not exist. Previously if filename did not exist all images in image table were processed.
> Fixed a bug when passing in filename that doesnt exist

- dlpy/model_conversion/write_onnx_model.py
Currently, src layers for concat are queried from model table to get the correct order.  Since the names are lower case while layer objects in DLPy are case sensitive, we ensure this does not cause a mismatch.
> Fix issue with lower case src layer names when writing concat op

- dlpy/attribute_utils.py
- dlpy/network.py
- dlpy/utils.py
This pull request opens the possibility of importing more complicated open source models in a variety of formats.  Previously, the import action created the attributes for an image classification model.  Now if the dataSpec parameter is supplied, more complicated scenarios (e.g. object detection) are supported.  The changes will be both forward and backward compatible because I test whether the import action supports the dataSpec parameter.  If it doesn't, I create the model attributes using Python code.  If it does, I let the action create the correct attributes.
I ran all the unit tests and there were no errors.
> Manage extended table attributes

- dlpy/model_conversion/onnx_graph.py
- dlpy/model_conversion/onnx_transforms.py
- dlpy/model_conversion/sas_onnx_parse.py
- dlpy/model_conversion/write_onnx_model.py
- dlpy/tests/test_model.py
- dlpy/tests/test_onnx_graph.py
- dlpy/tests/test_onnx_transforms.py
This pull request adds initial support for graph transformers when importing ONNX models.  These transformers rewrite subgraphs into a structure that is importable by DLPy.  Overview of the changes:  
New files:
onnx_graph.py - classes and utilities for onnx graph and node protos  
onnx_transforms.py - transformer base class and implementations of various transformers  
test_onnx_graph.py - tests for onnx_graph  
test_onnx_transforms.py - tests for onnx_transforms  
Changed:  
sas_onnx_parse.py - Add transformations when importing models  
write_onnx_model.py - Bug fixes:  
- Fix incorrect alpha value for leakyrelu activation  
- Fix imagescaler for single channel inputs  
- Fix missing output valueinfos for detection layer and loss-only output layer
> Add graph transformations for importing ONNX models

- dlpy/attribute_utils.py
- dlpy/model_conversion/sas_caffe_parse.py
This code update will fix open issue #120 and another Caffe conversion error I found.  The code update also brings the Python source code more in line with PEP-8 guidelines.  Most of the diffs you see are the result of changing variable names from camel case (aVarName) to PEP-8 standards (a_var_name).  The other substantial change was moving away from the use of the exec() function to the eval() function since the exec() function behavior changed between Python 2 and Python 3.
> Fix errors importing Caffe model

- dlpy/model_conversion/sas_keras_parse.py
- dlpy/model_conversion/write_sas_code.py
There is no equivalent function to Keras ZeroPadding2D layer in SAS deep learning actions.  However, convolution layer provides the ability to pad the input feature map(s).  Added code to associate ZeroPadding2D layer with subsequent convolution layer so padding and layer connections are correct.  I verified that a working copy of my changes functioned correctly with the ResNet50 model in the Keras applications folder.
> Add support for Keras ZeroPadding2D layer in automatic model translation

- dlpy/images.py
- dlpy/network.py
- dlpy/tests/test_model.py
- dlpy/utils.py
There was a bug dropping CASLIBs.  The previous code always dropped the specified CASLIB, whether it had be created within a DLPy function or not.  This led to some externally defined CASLIBs being dropped when they shouldn't have been.  The new code checks to see whether the CASLIB in question is a temporary CASLIB created by a DLPy function before dropping it.
> Fix bug dropping CASLIB.

- dlpy/images.py
- dlpy/utils.py
When a user supplies a previously defined CASLIB for certain DLPy functions, an unbound variable error can occur.  This problem is fixed by this pull request.
> External CASLIB dropped erroneously

- dlpy/network.py
The push fixes a bug in load_weights()
The issue happens when load caffemodel.h5 as a model and model weights.
The path option is a server-side path. 'if os.path.isfile(path):' is intended to check if the file exists but it is operating on client-side. I don't think we have a method to check server-side file by client python, so I remove the outer if statement.
> fix a bug in load_weights()

- doc/source/api.rst
Just modified the api.rst file so the new metrics and model.forecast will show up in the documentation.
> include the model.forecast and metrics into api.rst

- dlpy/applications.py
- dlpy/tests/test_applications.py
The affected files include:
dlpy/applications.py: added mobilenetv1, mobilenetv2 and shufflenetv1
dlpy/tests/test_applications.py: test cases covering the model functions
A related example will be pushed in the next pull request.
> support mobilenetv1 mobilnetv2 and shufflenetv1

- dlpy/tests/test_applications.py
- dlpy/tests/test_utils.py
- dlpy/utils.py
The affected files include:
dlpy/tests/test_utils.py: support nonsquare images and add error handler in several places.
dlpy/utils.py: corresponding tests
> support to create object detection table with non square images

- dlpy/network.py
- dlpy/tests/test_network.py
The push fixes an issue when stop_layers option in to_functional_model() is set to a layer other than the last layer. When it comes to the original output layer, I will check if the output layer can traverse to one of the input layers while removing the connections regarding the stop_layers. After the fix, you may still see the non-stop scenario, for example, in a residual block, shortcut layers are defined as stop_layers. I will think of a better way to handle the cases. The affected files include dlpy/network.py and dlpy/tests/test_network.py.
> fix to_functional_model bug

- dlpy/network.py
The name can be either "Leaky Activation function" or "Leaky Activation **F**unction", this change will handle both cases.
> Fix extracting name of leaky activation

- dlpy/speech.py
- dlpy/speech_utils.py
- dlpy/tests/test_speech.py
Ethem found a problem with test_speech.py. This happens when DLPY_DATA_DIR and DLPY_DATA_DIR_LOCAL don't point to the same position. Fixed.
Also push the change to check if the audio input has more than one channels. If the input is of stereo type, convert it to mono first.
> fix the unit test problem. add number of channels check and convert.

- dlpy/images.py
- dlpy/tests/test_imagetable.py
The changes will offer a flexible way to choose the images to be shown. Users write SAS where clause to make it. One example is dlpy/tests/test_imagetable.py test_show(). Besides, the push will fix a bug when nimages is greater than the number of observations.
> support where clause in imagetable.show() and fix a bug to show()

- dlpy/tests/test_utils.py
- dlpy/utils.py
This small change will adaptive set the length for the CAS variable "label" to the largest number of characters in all the labels provided.  Thus if the "label" column contains the the values "AA", "BB", "C" and "#", the number of characters for all observations will be set to 2.  This is the solution for issue #203 .
> Update to define better default for user-defined target labels

- dlpy/applications/yolo.py
- dlpy/layers.py
- dlpy/network.py
- dlpy/tests/test_applications.py
- dlpy/tests/test_model.py
- dlpy/tests/test_network.py
The push enables Recurrent layer to receive multiple inputs so that Functional API can be used for building mix CNN and RNN model in many usage cases. Besides, I add model_counter property for Model which reduces users load to change layers' name after several calls.
Some other changes include:
- correct YOLO model name
- remove the last row of print_summary
- error handlers for share_weights()
- test cases added and updated
> mix cnn and rnn connection support and other bugs fixed

- dlpy/applications/resnet.py
- dlpy/applications/vgg.py
- dlpy/caffe_models/model_resnet101.py
- dlpy/caffe_models/model_resnet152.py
- dlpy/caffe_models/model_resnet50.py
- dlpy/caffe_models/model_vgg16.py
- dlpy/layers.py
- dlpy/model.py
- dlpy/network.py
- dlpy/tests/test_applications.py
- dlpy/tests/test_utils.py
- dlpy/utils.py
This allows to add a reshape layer after the input layer to reshape the input tensor.
> Add reshape_after_input for resnet and vgg

- dlpy/images.py
- dlpy/layers.py
- dlpy/tests/test_imagetable.py
also remove the doc for the distance option in embedding loss since it is a hidden option.
run test_imagetables.py without any issue and also added a small test.
> added the id option to show the id column

- dlpy/model_conversion/onnx_graph.py
- dlpy/model_conversion/sas_onnx_parse.py
In other frameworks such as Tensorflow, the input shape for single channel images can be simply HxW.  Currently, DLPy expects CHW when parsing the onnx input.  In this case, we should check and automatically default the channels to 1.
> Update onnx import to better support single channel images

- dlpy/applications/densenet.py
- dlpy/applications/mobilenet.py
- dlpy/network.py
- dlpy/tests/test_applications.py
- dlpy/tests/test_network.py
The push includes changes as follows:
1. Support MobileNetV2_ONNX and DenseNet121_ONNX: The reason I create a new function for each of them is that those models are not identical to mobilenetv2 or densenet121. Essentially, the function takes the path of the model file and loads model table and model weights table if possible.
Model files, weights files, and readme files are put into /cas/DeepLearn/models/DenseNet121_ONNX and /cas/DeepLearn/models/MobileNetV2_ONNX.
2. Test cases for the two models.
3. Minor changes in dlpy/network.py. One place is to remove self.output_layers checking. It is unnecessary and will cause an attribute error when a model built by load() is compiled. Another place is to change 'Automatic' to 'auto' as a valid option.
> MobileNetV2_ONNX and DenseNet121_ONNX support

- dlpy/transformers/bert_model.py
- dlpy/transformers/bert_utils.py
This pull forces the encode_plus() function to return the special tokens mask that is used for BERT data preparation.  There is also a new warning message to indicate to the user whether the DLPy team has tested for compatibility with the version of the transformers package that the user has installed.
> Force return of special tokens mask

- dlpy/applications/resnet.py
- dlpy/model.py
Small bug fixes:
The ResNet50_Caffe model by default removes the ImageNet-trained output layer and replaces it with a similar layer with untrained parameters.  The name of the layer changes though, and this creates problems for the internal model representation on the Viya server side.  
If specified, the record_seed parameter causes random selection of records for each mini-batch.  We use a default value of 0, which means that the record_seed option is always used.  The fix overrides the default so the option is processed correctly by the deep learning actions.
> Fix bugs in ResNet50_Caffe and recordSeed.

- dlpy/audio.py
- dlpy/images.py
- dlpy/model.py
- dlpy/network.py
- dlpy/splitting.py
This commit adds to the docstrings of functions that use keyword arguments to pass options to CAS actions. In each docstring, I added a link to the the corresponding CAS documentation. The link points to the "default" documentation which is generally the most current LTS release. 
If you want to see a preview, I updated the HTML files in my gh-pages branch. They should be hosted at https://kybowm.github.io/python-dlpy but I don't see the changes yet even though I can confirm they are in my fork. Hopefully it's just taking the GitHub Pages server a while to refresh the content.
Let me know if you have any questions or concerns.
> Add documentation for action keyword arguments

- dlpy/images.py
This changes fixes an issue with the random_mutations function when
the 'inplace' parameter is set to False. The random_ratio parameter
needs to have an underscore since that is what is defined in the
function definition.
Signed-off-by: Avy Harvey <avy.harvey@sas.com>
> Fix typo in random_mutations function call.

- dlpy/tests/test_utils.py
- dlpy/utils.py
Added three more options: check_bbox, min_bbox_width and min_bbox_height to help filter bounding boxes.
If the width or height is lower than threshold, the corresponding bounding box won't be included in the data.
> enabled bounding box filtering when creating object detection table

- dlpy/applications/unet.py
This push enables output_image_type and output_image_prob for UNet models.
> enable png/base64 output for unet models

- dlpy/transformers/bert_model.py
When we need to use different type of BERT (cl-tohoku/bert-base-japanese, for instance), since they have different tokenizer from the one that the original BERT uses, users cannot call those models via DLPy's transformer. Auto classes can take care around this. (I think this also applies to roberta, distilbert as well, but didn't make it myself.)
> We should use Auto classes, shouldn't we?

- dlpy/layers.py
- dlpy/utils.py
The `collections.abc` module was created in Python 3.3 and certain classes were moved from `collections` to `collections.abc`, including `MutableMapping` and `Iterable`.  As of Python 3.10, those classes are **only** available through `collections.abc` which causes dlpy to fail to import on Python >= 3.10.
> updated collections to collections.abc
